name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch: 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Install npm dependencies
      run: yarn install
    - name: Grant execute permission for gradlew
      run: cd android && chmod +x gradlew
    - name: Build with Gradle
      run: cd android && ./gradlew assembleRelease
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.1
      with:
        # Artifact name
        name: release # optional, default is artifact
        # A file, directory or wildcard pattern that describes what to upload
        path: android/app/build/outputs/apk/release/app-release.apk
        
    - name: zip app-release.apk
      uses: vimtor/action-zip@v1
      with:
          files: android/app/build/outputs/apk/release/*.*
          dest: android/app/build/outputs/apk/release/release.zip
    - name: Upload Diawi
      # You may pin to the exact commit or the version.
      # uses: rnkdsh/action-upload-diawi@8434e3672357f1364f6f74ef78e37a50f7f34051
      uses: rnkdsh/action-upload-diawi@v1.3.0
      with:
        # Diawi API access token
        token: ${{ secrets.DIAWI_TOKEN }}
        # APK file to upload on Diawi
        file: android/app/build/outputs/apk/release/release.zip
        # Protect your app with a password. It will be required to access the installation page
        #password: # optional
        # Email addresses Diawi will send the result to (up to 5 separated by commas for starter/premium/enterprise accounts, 1 for free accounts)
        recipients: bharat.inani@atharvasystem.com # optional
        # Allow Diawi to display the app's icon on the wall of apps
        #wall_of_apps: # optional
        # Allow your testers to find the app on Diawi's mobile web app using their UDID (iOS only)
        #find_by_udid: # optional
        # Receive notifications each time someone installs the app (only starter/premium/enterprise accounts)
        #installation_notifications: # optional
        # Only parse the arguments without executing the upload
        #dry-run: # optional
        # Additional information to your users on this build: the comment will be displayed on the installation page
        #comment: # optional
